Выполнил домашнее задание 6 урока
Dysco76/GeekBrains-JS pull request #6
Opened 2021-03-10 17:38 UTC by Dysco76

2021-03-15 12:21 UTC, Om1X requested changes

2021-03-15 12:21 UTC, Om1X commented on Lesson6/HW/lesson6.html
> +          cart.addProduct(Object.assign({}, this.getClickedProduct(clicked)), this.getProductQuant(clicked));
cart - внешняя переменная, что не дает нам гибкости, если корзина будет названа по-другому, все перестанет работать, а править код внутри, для каждого из вариантов названия корзины не есть хорошо, нужна универсальность.

2021-03-15 12:21 UTC, Om1X commented on Lesson6/HW/lesson6.html
> +        if (!cart.countGoods() > 0) {
почему не this.countGoods()?

2021-03-15 12:43 UTC, Dysco76 commented on Lesson6/HW/lesson6.html
> +          cart.addProduct(Object.assign({}, this.getClickedProduct(clicked)), this.getProductQuant(clicked));
Подскажите, как здесь правильнее сделать?

2021-03-15 12:53 UTC, Dysco76 commented on Lesson6/HW/lesson6.html
> +          cart.addProduct(Object.assign({}, this.getClickedProduct(clicked)), this.getProductQuant(clicked));
Передавать в catalog.init() объект корзины как аргумент и далее передавать его же в catalog.addButtonHandler()? Так мы привязываемся не к переменной корзины, а к аргументу, через который в каталог передадут корзину.

2021-03-17 16:46 UTC, Om1X requested changes

2021-03-17 16:46 UTC, Om1X commented on Lesson6/HW/lesson6.html
> +      init(cartObject, photosObject) {
photosObject где-то потерялся

2021-03-17 17:25 UTC, merged